export interface GstInvoiceGrid{
invoice_Id: number
invoice_Number: string
company_Id: number
company_Code: string
cost_Center_Mapping_Id: number
map_Name: string
city_Id: number
city_Name: string
financial_Year_Id: number
pay_Period_Id: number
pay_Period: string
invoice_Type_Id: number
invoiceType: string
invoice_Date: string
particulars: string
amount: number
iGST_Percentage: number
iGST_Amount: number
service_Charge: number
service_Charge_Amount: number
sourcing_Fee: number
sourcing_Fee_Amount: number
no_Of_Employees: number
net_Amount: number
input_No: number
employee_PF: number
employer_PF: number
dO_Number: string
status: string
isActive: boolean
isLocked: boolean
group_Detail_Id: number
group_Name: string
crn_Number: number
crn_IRN_Status: string
crn_IRN_Number: number
crn_IRN_Cancel_Date: string
sap_Invoice_Number: string
sap_Account_Number: string
sap_Cancel_Document: string
sap_Credit_Note_Document: string
bGVBL: number
aSTFEE: number
dISCT1: number
dISCT2: number
iDCARD: number
eMAIL: number
rEGFEE: number
tRNFEE: number
gGDBT: number
pPEKIT: number
vMSFEE: number
cALCRG: number
cALRT: number
}